[package]
name = "agc037"
version = "0.1.0"
authors = ["himkt <himkt@cookpad.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'
